-- MySQL Script generated by MySQL Workbench
-- Qua 14 Mai 2014 16:40:34 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema locacao
-- -----------------------------------------------------
-- Base para controle de locação de veículos.
CREATE SCHEMA IF NOT EXISTS `locacao` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `locacao` ;

-- -----------------------------------------------------
-- Table `locacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`usuario` (
  `id` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `locacao`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`cliente` (
  `id` INT NOT NULL auto_increment,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `tipo` CHAR(2) NOT NULL,

  `cpf` BIGINT(11) DEFAULT NULL,
  `nome` VARCHAR(45) DEFAULT NULL,  
  `rg` VARCHAR(45) DEFAULT NULL,
  `habilitacao` VARCHAR(45) DEFAULT NULL,
  `data_nascimento` VARCHAR(45) DEFAULT NULL,
  `genero` VARCHAR(45) DEFAULT NULL,
  
  `cnpj` BIGINT(14) DEFAULT NULL,
  `razao_social` VARCHAR(45) DEFAULT NULL,
  `nome_comercial` VARCHAR(45) DEFAULT NULL,  
  `inscricao_estadual` VARCHAR(45) DEFAULT NULL,
  `data_fundacao` VARCHAR(45) DEFAULT NULL,
  `numero_funcionarios` INT DEFAULT 0,
   
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`emprestimo` (
  `id` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `modelo_veiculo` VARCHAR(45) NOT NULL,
  `data_inicial` DATE NOT NULL,
  `hora` TIMESTAMP NOT NULL,
  `local_emprestimo` VARCHAR(45) NOT NULL,
  `data_devolucao` DATE NOT NULL,
  `hora` TIMESTAMP NOT NULL,
  `tipo_tarifa` VARCHAR(45) NOT NULL,
  `pais_devolucao` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id_cliente`)
    REFERENCES `locacao`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`reserva` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` INT NOT NULL,
  `passaporte` INT NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `ano` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `periodo_locacao` DATETIME NOT NULL,
  `cliente_nome` INT NOT NULL,
  PRIMARY KEY (`id`, `cliente_nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`grupos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`veiculo` (
  `id` INT NOT NULL auto_increment,
  `chassi` VARCHAR(45) NOT NULL,
  `placa` VARCHAR(45) NOT NULL,
  `km` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `fabricante` VARCHAR(45) NOT NULL,
  `tarifa` VARCHAR(45) NOT NULL,
  `taxa` VARCHAR(45) NOT NULL,
  `combustivel` VARCHAR(45) NOT NULL,
  `portas` INT NOT NULL,
  `ano_modelo` INT NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `renavam` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `disponivel` TINYINT(1) NOT NULL,
  `estoque` INT NOT NULL,
  `observacoes` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`devolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`devolucao` (
  `id` INT NOT NULL,
  `numero_locacao` INT NOT NULL,
  `emprestimo_id` INT NOT NULL,
  `emprestimo_cliente_nome` INT NOT NULL,
  PRIMARY KEY (`id`, `emprestimo_id`, `emprestimo_cliente_nome`),
  INDEX `fk_devolucao_emprestimo1_idx` (`emprestimo_id` ASC, `emprestimo_cliente_nome` ASC),
  CONSTRAINT `fk_devolucao_emprestimo1`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `locacao`.`emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`pagamento` (
  `id` INT NOT NULL,
  `nome_titular` VARCHAR(45) NULL,
  `cpf` INT NULL,
  `nome_banco` VARCHAR(45) NULL DEFAULT NULL,
  `agencia` VARCHAR(45) NULL DEFAULT NULL,
  `conta_corrente` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` INT NULL DEFAULT NULL,
  `bandeira_cartao` VARCHAR(45) NULL DEFAULT NULL,
  `numero_cartao` INT NULL DEFAULT NULL,
  `validade` DATETIME NULL DEFAULT NULL,
  `cod_seguranca` INT NULL DEFAULT NULL,
  `devolucao_id` INT NOT NULL,
  `devolucao_emprestimo_id` INT NOT NULL,
  `devolucao_emprestimo_cliente_nome` INT NOT NULL,
  PRIMARY KEY (`id`, `devolucao_id`, `devolucao_emprestimo_id`, `devolucao_emprestimo_cliente_nome`),
  INDEX `fk_pagamento_devolucao1_idx` (`devolucao_id` ASC, `devolucao_emprestimo_id` ASC, `devolucao_emprestimo_cliente_nome` ASC),
  CONSTRAINT `fk_pagamento_devolucao1`
    FOREIGN KEY (`devolucao_id` , `devolucao_emprestimo_id` , `devolucao_emprestimo_cliente_nome`)
    REFERENCES `locacao`.`devolucao` (`id` , `emprestimo_id` , `emprestimo_cliente_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`idioma` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`agencia` (
  `codigo` INT NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `emprestimo_id` INT NOT NULL,
  `idioma_id` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_agencia_emprestimo1_idx` (`emprestimo_id` ASC),
  INDEX `fk_agencia_idioma1_idx` (`idioma_id` ASC),
  CONSTRAINT `fk_agencia_emprestimo1`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `locacao`.`emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agencia_idioma1`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `locacao`.`idioma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`itensEmprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`itensEmprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emprestimo_id` INT NOT NULL,
  `reserva_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  `veiculo_grupos_id` INT NOT NULL,
  `veiculo_itensEmprestimo_reserva_cliente_nome` INT NOT NULL,
  PRIMARY KEY (`id`, `emprestimo_id`, `reserva_id`, `veiculo_id`, `veiculo_grupos_id`, `veiculo_itensEmprestimo_reserva_cliente_nome`),
  INDEX `fk_itensEmprestimo_emprestimo1_idx` (`emprestimo_id` ASC),
  INDEX `fk_itensEmprestimo_reserva1_idx` (`reserva_id` ASC),
  INDEX `fk_itensEmprestimo_veiculo1_idx` (`veiculo_id` ASC, `veiculo_grupos_id` ASC, `veiculo_itensEmprestimo_reserva_cliente_nome` ASC),
  CONSTRAINT `fk_itensEmprestimo_emprestimo1`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `locacao`.`emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itensEmprestimo_reserva1`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `locacao`.`reserva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itensEmprestimo_veiculo1`
    FOREIGN KEY (`veiculo_id` , `veiculo_grupos_id` , `veiculo_itensEmprestimo_reserva_cliente_nome`)
    REFERENCES `locacao`.`veiculo` (`id` , `grupos_id` , `itensEmprestimo_reserva_cliente_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`acessorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`acessorios` (
  `id` INT NOT NULL,
  `id_veiculo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`acessorios_has_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`acessorios_has_veiculo` (
  `acessorios_id` INT NOT NULL,
  `veiculo_id_veiculo` INT NOT NULL,
  PRIMARY KEY (`acessorios_id`, `veiculo_id_veiculo`),
  INDEX `fk_acessorios_has_veiculo_veiculo1_idx` (`veiculo_id_veiculo` ASC),
  INDEX `fk_acessorios_has_veiculo_acessorios_idx` (`acessorios_id` ASC),
  CONSTRAINT `fk_acessorios_has_veiculo_acessorios`
    FOREIGN KEY (`acessorios_id`)
    REFERENCES `locacao`.`acessorios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acessorios_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_id_veiculo`)
    REFERENCES `locacao`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `locacao`.`serasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `locacao`.`serasa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NULL,
  `cliente_cpf` INT NOT NULL,
  PRIMARY KEY (`id`, `cliente_cpf`),
  INDEX `fk_serasa_cliente1_idx` (`cliente_cpf` ASC),
  CONSTRAINT `fk_serasa_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `locacao`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Dados para teste
-- -----------------------------------------------------
insert into `locacao`.`usuario`(nome, email, senha) values("Gabriel", "gabriel@provedor.com", "123");


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
